//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace CRUD2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class User
    {
        public int userId { get; set; }
        [Required(ErrorMessage = "Name is required")]
        public string name { get; set; }
        [Required(ErrorMessage = "date of birth is required")]
        public DateTime dob { get; set; }
        public Nullable<bool> gender { get; set; }
        [DisplayName("Uploaded file")]
        public string profile_photo { get; set; }
        public HttpPostedFileBase imageFile { get; set; }
    }
}
